# permissions for end users to edit spamtests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spamtest-editor-role
rules:
- apiGroups:
  - test.jaypoulz.me
  resources:
  - spamtests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - test.jaypoulz.me
  resources:
  - spamtests/status
  verbs:
  - get
