# permissions for end users to view spamtests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spamtest-viewer-role
rules:
- apiGroups:
  - test.jaypoulz.me
  resources:
  - spamtests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - test.jaypoulz.me
  resources:
  - spamtests/status
  verbs:
  - get
